/**
 * This custom format creates an Android colors.xml file with the colours 
 * defined by the Teamwork Design System so they can be referenced in the app
 * via `R.color.color.light_color_link_default` etc.
 */
module.exports = function ({ dictionary, options }) {
  return `<?xml version="1.0" encoding="UTF-8"?>

<!-- colours generated by the Teamwork Design System -->
<resources>\n` +
    dictionary.allProperties.map(token => {
      return `\t<color name="${token.name}">${token.value}</color>`;
    }).join("\n") + `\n</resources>\n`;
}
